# Generated by Django 4.2.3 on 2023-07-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements_66', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
