# Generated by Django 4.2.4 on 2023-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements_66', '0003_timetables_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements_66/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
